package sop_corba;


/**
* sop_corba/_GestionAnteproyectosStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaz.idl
* martes 30 de julio de 2019 20H58' COT
*/

public class _GestionAnteproyectosStub extends org.omg.CORBA.portable.ObjectImpl implements sop_corba.GestionAnteproyectos
{

  public sop_corba.GestionAnteproyectosPackage.usuarioDTO verificarCredenciales (String usuario, String contrasenia)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("verificarCredenciales", true);
                $out.write_string (usuario);
                $out.write_string (contrasenia);
                $in = _invoke ($out);
                sop_corba.GestionAnteproyectosPackage.usuarioDTO $result = sop_corba.GestionAnteproyectosPackage.usuarioDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return verificarCredenciales (usuario, contrasenia        );
            } finally {
                _releaseReply ($in);
            }
  } // verificarCredenciales

  public boolean registrarAnteproyecto (sop_corba.GestionAnteproyectosPackage.anteproyectoDTO objAnteproyecto)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registrarAnteproyecto", true);
                sop_corba.GestionAnteproyectosPackage.anteproyectoDTOHelper.write ($out, objAnteproyecto);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return registrarAnteproyecto (objAnteproyecto        );
            } finally {
                _releaseReply ($in);
            }
  } // registrarAnteproyecto

  public boolean registrarUsuario (sop_corba.GestionAnteproyectosPackage.usuarioDTO objUsuario)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registrarUsuario", true);
                sop_corba.GestionAnteproyectosPackage.usuarioDTOHelper.write ($out, objUsuario);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return registrarUsuario (objUsuario        );
            } finally {
                _releaseReply ($in);
            }
  } // registrarUsuario

  public sop_corba.GestionAnteproyectosPackage.anteproyectoDTO[] listarAnteproyectos ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listarAnteproyectos", true);
                $in = _invoke ($out);
                sop_corba.GestionAnteproyectosPackage.anteproyectoDTO $result[] = sop_corba.GestionAnteproyectosPackage.ListaAnteproyectosHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listarAnteproyectos (        );
            } finally {
                _releaseReply ($in);
            }
  } // listarAnteproyectos

  public sop_corba.GestionAnteproyectosPackage.anteproyectoDTO buscarAnteproyecto (int codigo)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("buscarAnteproyecto", true);
                $out.write_long (codigo);
                $in = _invoke ($out);
                sop_corba.GestionAnteproyectosPackage.anteproyectoDTO $result = sop_corba.GestionAnteproyectosPackage.anteproyectoDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return buscarAnteproyecto (codigo        );
            } finally {
                _releaseReply ($in);
            }
  } // buscarAnteproyecto

  public boolean asignarEvaluador (int codigo, sop_corba.GestionAnteproyectosPackage.evaluadoresDTO objEvaluador)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("asignarEvaluador", true);
                $out.write_long (codigo);
                sop_corba.GestionAnteproyectosPackage.evaluadoresDTOHelper.write ($out, objEvaluador);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return asignarEvaluador (codigo, objEvaluador        );
            } finally {
                _releaseReply ($in);
            }
  } // asignarEvaluador

  public int numeroFilas ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("numeroFilas", true);
                $in = _invoke ($out);
                int $result = $in.read_long ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return numeroFilas (        );
            } finally {
                _releaseReply ($in);
            }
  } // numeroFilas

  public sop_corba.GestionAnteproyectosPackage.evaluadoresDTO buscarEvaluador (int codigo)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("buscarEvaluador", true);
                $out.write_long (codigo);
                $in = _invoke ($out);
                sop_corba.GestionAnteproyectosPackage.evaluadoresDTO $result = sop_corba.GestionAnteproyectosPackage.evaluadoresDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return buscarEvaluador (codigo        );
            } finally {
                _releaseReply ($in);
            }
  } // buscarEvaluador

  public boolean cambiarConceptoAnteproyecto (int codigo)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("cambiarConceptoAnteproyecto", true);
                $out.write_long (codigo);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return cambiarConceptoAnteproyecto (codigo        );
            } finally {
                _releaseReply ($in);
            }
  } // cambiarConceptoAnteproyecto

  public boolean guardarCredencialesUsuario (String usuario, String contrasenia)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("guardarCredencialesUsuario", true);
                $out.write_string (usuario);
                $out.write_string (contrasenia);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return guardarCredencialesUsuario (usuario, contrasenia        );
            } finally {
                _releaseReply ($in);
            }
  } // guardarCredencialesUsuario

  public boolean aniadirConceptoEvaluador (int codigo, String concepto)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("aniadirConceptoEvaluador", true);
                $out.write_long (codigo);
                $out.write_string (concepto);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return aniadirConceptoEvaluador (codigo, concepto        );
            } finally {
                _releaseReply ($in);
            }
  } // aniadirConceptoEvaluador

  public sop_corba.GestionAnteproyectosPackage.usuarioIngresadoDTO recuperarUsuario ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("recuperarUsuario", true);
                $in = _invoke ($out);
                sop_corba.GestionAnteproyectosPackage.usuarioIngresadoDTO $result = sop_corba.GestionAnteproyectosPackage.usuarioIngresadoDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return recuperarUsuario (        );
            } finally {
                _releaseReply ($in);
            }
  } // recuperarUsuario

  public sop_corba.GestionAnteproyectosPackage.usuarioDTO[] listarUsuarios ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listarUsuarios", true);
                $in = _invoke ($out);
                sop_corba.GestionAnteproyectosPackage.usuarioDTO $result[] = sop_corba.GestionAnteproyectosPackage.ListaUsuariosHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listarUsuarios (        );
            } finally {
                _releaseReply ($in);
            }
  } // listarUsuarios

  public sop_corba.GestionAnteproyectosPackage.evaluadoresDTO[] listarEvaluadores ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listarEvaluadores", true);
                $in = _invoke ($out);
                sop_corba.GestionAnteproyectosPackage.evaluadoresDTO $result[] = sop_corba.GestionAnteproyectosPackage.ListaEvaluadoresHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listarEvaluadores (        );
            } finally {
                _releaseReply ($in);
            }
  } // listarEvaluadores

  public sop_corba.GestionAnteproyectosPackage.usuarioIngresadoDTO[] listarUsuariosIngresados ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listarUsuariosIngresados", true);
                $in = _invoke ($out);
                sop_corba.GestionAnteproyectosPackage.usuarioIngresadoDTO $result[] = sop_corba.GestionAnteproyectosPackage.ListaUsuariosIngresadosHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listarUsuariosIngresados (        );
            } finally {
                _releaseReply ($in);
            }
  } // listarUsuariosIngresados

  public boolean registrarCliente (sop_corba.ClienteInt objcllbck)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registrarCliente", true);
                sop_corba.ClienteIntHelper.write ($out, objcllbck);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return registrarCliente (objcllbck        );
            } finally {
                _releaseReply ($in);
            }
  } // registrarCliente

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/GestionAnteproyectos:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _GestionAnteproyectosStub
