package sop_corba;


/**
* sop_corba/GestionAnteproyectosHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaz.idl
* martes 30 de julio de 2019 20H58' COT
*/

abstract public class GestionAnteproyectosHelper
{
  private static String  _id = "IDL:sop_corba/GestionAnteproyectos:1.0";

  public static void insert (org.omg.CORBA.Any a, sop_corba.GestionAnteproyectos that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static sop_corba.GestionAnteproyectos extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (sop_corba.GestionAnteproyectosHelper.id (), "GestionAnteproyectos");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static sop_corba.GestionAnteproyectos read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GestionAnteproyectosStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, sop_corba.GestionAnteproyectos value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static sop_corba.GestionAnteproyectos narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof sop_corba.GestionAnteproyectos)
      return (sop_corba.GestionAnteproyectos)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      sop_corba._GestionAnteproyectosStub stub = new sop_corba._GestionAnteproyectosStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static sop_corba.GestionAnteproyectos unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof sop_corba.GestionAnteproyectos)
      return (sop_corba.GestionAnteproyectos)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      sop_corba._GestionAnteproyectosStub stub = new sop_corba._GestionAnteproyectosStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
