package sop_corba;


/**
* sop_corba/GestionAnteproyectos.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaz.idl
* martes 30 de julio de 2019 20H58' COT
*/

public interface GestionAnteproyectos extends GestionAnteproyectosOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionAnteproyectos
