package sop_corba;


/**
* sop_corba/GestionAnteproyectosPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaz.idl
* martes 30 de julio de 2019 20H58' COT
*/

public abstract class GestionAnteproyectosPOA extends org.omg.PortableServer.Servant
 implements sop_corba.GestionAnteproyectosOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("verificarCredenciales", new java.lang.Integer (0));
    _methods.put ("registrarAnteproyecto", new java.lang.Integer (1));
    _methods.put ("registrarUsuario", new java.lang.Integer (2));
    _methods.put ("listarAnteproyectos", new java.lang.Integer (3));
    _methods.put ("buscarAnteproyecto", new java.lang.Integer (4));
    _methods.put ("asignarEvaluador", new java.lang.Integer (5));
    _methods.put ("numeroFilas", new java.lang.Integer (6));
    _methods.put ("buscarEvaluador", new java.lang.Integer (7));
    _methods.put ("cambiarConceptoAnteproyecto", new java.lang.Integer (8));
    _methods.put ("guardarCredencialesUsuario", new java.lang.Integer (9));
    _methods.put ("aniadirConceptoEvaluador", new java.lang.Integer (10));
    _methods.put ("recuperarUsuario", new java.lang.Integer (11));
    _methods.put ("listarUsuarios", new java.lang.Integer (12));
    _methods.put ("listarEvaluadores", new java.lang.Integer (13));
    _methods.put ("listarUsuariosIngresados", new java.lang.Integer (14));
    _methods.put ("registrarCliente", new java.lang.Integer (15));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/GestionAnteproyectos/verificarCredenciales
       {
         String usuario = in.read_string ();
         String contrasenia = in.read_string ();
         sop_corba.GestionAnteproyectosPackage.usuarioDTO $result = null;
         $result = this.verificarCredenciales (usuario, contrasenia);
         out = $rh.createReply();
         sop_corba.GestionAnteproyectosPackage.usuarioDTOHelper.write (out, $result);
         break;
       }

       case 1:  // sop_corba/GestionAnteproyectos/registrarAnteproyecto
       {
         sop_corba.GestionAnteproyectosPackage.anteproyectoDTO objAnteproyecto = sop_corba.GestionAnteproyectosPackage.anteproyectoDTOHelper.read (in);
         boolean $result = false;
         $result = this.registrarAnteproyecto (objAnteproyecto);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // sop_corba/GestionAnteproyectos/registrarUsuario
       {
         sop_corba.GestionAnteproyectosPackage.usuarioDTO objUsuario = sop_corba.GestionAnteproyectosPackage.usuarioDTOHelper.read (in);
         boolean $result = false;
         $result = this.registrarUsuario (objUsuario);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // sop_corba/GestionAnteproyectos/listarAnteproyectos
       {
         sop_corba.GestionAnteproyectosPackage.anteproyectoDTO $result[] = null;
         $result = this.listarAnteproyectos ();
         out = $rh.createReply();
         sop_corba.GestionAnteproyectosPackage.ListaAnteproyectosHelper.write (out, $result);
         break;
       }

       case 4:  // sop_corba/GestionAnteproyectos/buscarAnteproyecto
       {
         int codigo = in.read_long ();
         sop_corba.GestionAnteproyectosPackage.anteproyectoDTO $result = null;
         $result = this.buscarAnteproyecto (codigo);
         out = $rh.createReply();
         sop_corba.GestionAnteproyectosPackage.anteproyectoDTOHelper.write (out, $result);
         break;
       }

       case 5:  // sop_corba/GestionAnteproyectos/asignarEvaluador
       {
         int codigo = in.read_long ();
         sop_corba.GestionAnteproyectosPackage.evaluadoresDTO objEvaluador = sop_corba.GestionAnteproyectosPackage.evaluadoresDTOHelper.read (in);
         boolean $result = false;
         $result = this.asignarEvaluador (codigo, objEvaluador);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 6:  // sop_corba/GestionAnteproyectos/numeroFilas
       {
         int $result = (int)0;
         $result = this.numeroFilas ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 7:  // sop_corba/GestionAnteproyectos/buscarEvaluador
       {
         int codigo = in.read_long ();
         sop_corba.GestionAnteproyectosPackage.evaluadoresDTO $result = null;
         $result = this.buscarEvaluador (codigo);
         out = $rh.createReply();
         sop_corba.GestionAnteproyectosPackage.evaluadoresDTOHelper.write (out, $result);
         break;
       }

       case 8:  // sop_corba/GestionAnteproyectos/cambiarConceptoAnteproyecto
       {
         int codigo = in.read_long ();
         boolean $result = false;
         $result = this.cambiarConceptoAnteproyecto (codigo);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 9:  // sop_corba/GestionAnteproyectos/guardarCredencialesUsuario
       {
         String usuario = in.read_string ();
         String contrasenia = in.read_string ();
         boolean $result = false;
         $result = this.guardarCredencialesUsuario (usuario, contrasenia);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 10:  // sop_corba/GestionAnteproyectos/aniadirConceptoEvaluador
       {
         int codigo = in.read_long ();
         String concepto = in.read_string ();
         boolean $result = false;
         $result = this.aniadirConceptoEvaluador (codigo, concepto);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 11:  // sop_corba/GestionAnteproyectos/recuperarUsuario
       {
         sop_corba.GestionAnteproyectosPackage.usuarioIngresadoDTO $result = null;
         $result = this.recuperarUsuario ();
         out = $rh.createReply();
         sop_corba.GestionAnteproyectosPackage.usuarioIngresadoDTOHelper.write (out, $result);
         break;
       }

       case 12:  // sop_corba/GestionAnteproyectos/listarUsuarios
       {
         sop_corba.GestionAnteproyectosPackage.usuarioDTO $result[] = null;
         $result = this.listarUsuarios ();
         out = $rh.createReply();
         sop_corba.GestionAnteproyectosPackage.ListaUsuariosHelper.write (out, $result);
         break;
       }

       case 13:  // sop_corba/GestionAnteproyectos/listarEvaluadores
       {
         sop_corba.GestionAnteproyectosPackage.evaluadoresDTO $result[] = null;
         $result = this.listarEvaluadores ();
         out = $rh.createReply();
         sop_corba.GestionAnteproyectosPackage.ListaEvaluadoresHelper.write (out, $result);
         break;
       }

       case 14:  // sop_corba/GestionAnteproyectos/listarUsuariosIngresados
       {
         sop_corba.GestionAnteproyectosPackage.usuarioIngresadoDTO $result[] = null;
         $result = this.listarUsuariosIngresados ();
         out = $rh.createReply();
         sop_corba.GestionAnteproyectosPackage.ListaUsuariosIngresadosHelper.write (out, $result);
         break;
       }

       case 15:  // sop_corba/GestionAnteproyectos/registrarCliente
       {
         sop_corba.ClienteInt objcllbck = sop_corba.ClienteIntHelper.read (in);
         boolean $result = false;
         $result = this.registrarCliente (objcllbck);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/GestionAnteproyectos:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GestionAnteproyectos _this() 
  {
    return GestionAnteproyectosHelper.narrow(
    super._this_object());
  }

  public GestionAnteproyectos _this(org.omg.CORBA.ORB orb) 
  {
    return GestionAnteproyectosHelper.narrow(
    super._this_object(orb));
  }


} // class GestionAnteproyectosPOA
