package sop_corba;

/**
* sop_corba/GestionAnteproyectosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaz.idl
* martes 30 de julio de 2019 20H58' COT
*/

public final class GestionAnteproyectosHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.GestionAnteproyectos value = null;

  public GestionAnteproyectosHolder ()
  {
  }

  public GestionAnteproyectosHolder (sop_corba.GestionAnteproyectos initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.GestionAnteproyectosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.GestionAnteproyectosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.GestionAnteproyectosHelper.type ();
  }

}
