package sop_corba;


/**
* sop_corba/GestionAnteproyectosOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaz.idl
* martes 30 de julio de 2019 20H58' COT
*/

public interface GestionAnteproyectosOperations 
{
  sop_corba.GestionAnteproyectosPackage.usuarioDTO verificarCredenciales (String usuario, String contrasenia);
  boolean registrarAnteproyecto (sop_corba.GestionAnteproyectosPackage.anteproyectoDTO objAnteproyecto);
  boolean registrarUsuario (sop_corba.GestionAnteproyectosPackage.usuarioDTO objUsuario);
  sop_corba.GestionAnteproyectosPackage.anteproyectoDTO[] listarAnteproyectos ();
  sop_corba.GestionAnteproyectosPackage.anteproyectoDTO buscarAnteproyecto (int codigo);
  boolean asignarEvaluador (int codigo, sop_corba.GestionAnteproyectosPackage.evaluadoresDTO objEvaluador);
  int numeroFilas ();
  sop_corba.GestionAnteproyectosPackage.evaluadoresDTO buscarEvaluador (int codigo);
  boolean cambiarConceptoAnteproyecto (int codigo);
  boolean guardarCredencialesUsuario (String usuario, String contrasenia);
  boolean aniadirConceptoEvaluador (int codigo, String concepto);
  sop_corba.GestionAnteproyectosPackage.usuarioIngresadoDTO recuperarUsuario ();
  sop_corba.GestionAnteproyectosPackage.usuarioDTO[] listarUsuarios ();
  sop_corba.GestionAnteproyectosPackage.evaluadoresDTO[] listarEvaluadores ();
  sop_corba.GestionAnteproyectosPackage.usuarioIngresadoDTO[] listarUsuariosIngresados ();
  boolean registrarCliente (sop_corba.ClienteInt objcllbck);
} // interface GestionAnteproyectosOperations
