package sop_corba.GestionAnteproyectosPackage;


/**
* sop_corba/GestionAnteproyectosPackage/anteproyectoDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaz.idl
* martes 30 de julio de 2019 20H58' COT
*/

public final class anteproyectoDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int codigo = (int)0;
  public String titulo = "";
  public String modalidad = "";
  public String estudiante_1 = "";
  public String estudiante_2 = "";
  public String director = "";
  public String co_director = "";
  public String fechaIngreso = "";
  public String fechaAprobacion = "";
  public int concepto = (int)0;
  public int estado = (int)0;
  public int numeroRevision = (int)0;

  public anteproyectoDTO ()
  {
  } // ctor

  public anteproyectoDTO (int _codigo, String _titulo, String _modalidad, String _estudiante_1, String _estudiante_2, String _director, String _co_director, String _fechaIngreso, String _fechaAprobacion, int _concepto, int _estado, int _numeroRevision)
  {
    codigo = _codigo;
    titulo = _titulo;
    modalidad = _modalidad;
    estudiante_1 = _estudiante_1;
    estudiante_2 = _estudiante_2;
    director = _director;
    co_director = _co_director;
    fechaIngreso = _fechaIngreso;
    fechaAprobacion = _fechaAprobacion;
    concepto = _concepto;
    estado = _estado;
    numeroRevision = _numeroRevision;
  } // ctor

    public int getCodigo() {
        return codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    public String getTitulo() {
        return titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public String getModalidad() {
        return modalidad;
    }

    public void setModalidad(String modalidad) {
        this.modalidad = modalidad;
    }

    public String getEstudiante_1() {
        return estudiante_1;
    }

    public void setEstudiante_1(String estudiante_1) {
        this.estudiante_1 = estudiante_1;
    }

    public String getEstudiante_2() {
        return estudiante_2;
    }

    public void setEstudiante_2(String estudiante_2) {
        this.estudiante_2 = estudiante_2;
    }

    public String getDirector() {
        return director;
    }

    public void setDirector(String director) {
        this.director = director;
    }

    public String getCo_director() {
        return co_director;
    }

    public void setCo_director(String co_director) {
        this.co_director = co_director;
    }

    public String getFechaIngreso() {
        return fechaIngreso;
    }

    public void setFechaIngreso(String fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    public String getFechaAprobacion() {
        return fechaAprobacion;
    }

    public void setFechaAprobacion(String fechaAprobacion) {
        this.fechaAprobacion = fechaAprobacion;
    }

    public int getConcepto() {
        return concepto;
    }

    public void setConcepto(int concepto) {
        this.concepto = concepto;
    }

    public int getEstado() {
        return estado;
    }

    public void setEstado(int estado) {
        this.estado = estado;
    }

    public int getNumeroRevision() {
        return numeroRevision;
    }

    public void setNumeroRevision(int numeroRevision) {
        this.numeroRevision = numeroRevision;
    }

  
} // class anteproyectoDTO
