package sop_corba.GestionAnteproyectosPackage;

/**
* sop_corba/GestionAnteproyectosPackage/anteproyectoDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaz.idl
* martes 30 de julio de 2019 20H58' COT
*/

public final class anteproyectoDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.GestionAnteproyectosPackage.anteproyectoDTO value = null;

  public anteproyectoDTOHolder ()
  {
  }

  public anteproyectoDTOHolder (sop_corba.GestionAnteproyectosPackage.anteproyectoDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.GestionAnteproyectosPackage.anteproyectoDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.GestionAnteproyectosPackage.anteproyectoDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.GestionAnteproyectosPackage.anteproyectoDTOHelper.type ();
  }

}
