package sop_corba.GestionAnteproyectosPackage;


/**
* sop_corba/GestionAnteproyectosPackage/anteproyectoDTOHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaz.idl
* martes 30 de julio de 2019 20H58' COT
*/

abstract public class anteproyectoDTOHelper
{
  private static String  _id = "IDL:sop_corba/GestionAnteproyectos/anteproyectoDTO:1.0";

  public static void insert (org.omg.CORBA.Any a, sop_corba.GestionAnteproyectosPackage.anteproyectoDTO that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static sop_corba.GestionAnteproyectosPackage.anteproyectoDTO extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [12];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "codigo",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "titulo",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "modalidad",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "estudiante_1",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "estudiante_2",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[5] = new org.omg.CORBA.StructMember (
            "director",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[6] = new org.omg.CORBA.StructMember (
            "co_director",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[7] = new org.omg.CORBA.StructMember (
            "fechaIngreso",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[8] = new org.omg.CORBA.StructMember (
            "fechaAprobacion",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[9] = new org.omg.CORBA.StructMember (
            "concepto",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[10] = new org.omg.CORBA.StructMember (
            "estado",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[11] = new org.omg.CORBA.StructMember (
            "numeroRevision",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (sop_corba.GestionAnteproyectosPackage.anteproyectoDTOHelper.id (), "anteproyectoDTO", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static sop_corba.GestionAnteproyectosPackage.anteproyectoDTO read (org.omg.CORBA.portable.InputStream istream)
  {
    sop_corba.GestionAnteproyectosPackage.anteproyectoDTO value = new sop_corba.GestionAnteproyectosPackage.anteproyectoDTO ();
    value.codigo = istream.read_long ();
    value.titulo = istream.read_string ();
    value.modalidad = istream.read_string ();
    value.estudiante_1 = istream.read_string ();
    value.estudiante_2 = istream.read_string ();
    value.director = istream.read_string ();
    value.co_director = istream.read_string ();
    value.fechaIngreso = istream.read_string ();
    value.fechaAprobacion = istream.read_string ();
    value.concepto = istream.read_long ();
    value.estado = istream.read_long ();
    value.numeroRevision = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, sop_corba.GestionAnteproyectosPackage.anteproyectoDTO value)
  {
    ostream.write_long (value.codigo);
    ostream.write_string (value.titulo);
    ostream.write_string (value.modalidad);
    ostream.write_string (value.estudiante_1);
    ostream.write_string (value.estudiante_2);
    ostream.write_string (value.director);
    ostream.write_string (value.co_director);
    ostream.write_string (value.fechaIngreso);
    ostream.write_string (value.fechaAprobacion);
    ostream.write_long (value.concepto);
    ostream.write_long (value.estado);
    ostream.write_long (value.numeroRevision);
  }

}
