package sop_corba.GestionAnteproyectosPackage;

/**
* sop_corba/GestionAnteproyectosPackage/evaluadoresDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaz.idl
* martes 30 de julio de 2019 20H58' COT
*/

public final class evaluadoresDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.GestionAnteproyectosPackage.evaluadoresDTO value = null;

  public evaluadoresDTOHolder ()
  {
  }

  public evaluadoresDTOHolder (sop_corba.GestionAnteproyectosPackage.evaluadoresDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.GestionAnteproyectosPackage.evaluadoresDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.GestionAnteproyectosPackage.evaluadoresDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.GestionAnteproyectosPackage.evaluadoresDTOHelper.type ();
  }

}
