package sop_corba.GestionAnteproyectosPackage;


/**
* sop_corba/GestionAnteproyectosPackage/evaluadoresDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaz.idl
* martes 30 de julio de 2019 20H58' COT
*/

public final class evaluadoresDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int codigo = (int)0;
  public String evaluador_1 = "";
  public String conceptoEvaluador_1 = "";
  public String fechaRevision_1 = "";
  public String evaluador_2 = "";
  public String conceptoEvaluador_2 = "";
  public String fechaRevision_2 = "";

  public evaluadoresDTO ()
  {
  } // ctor

  public evaluadoresDTO (int _codigo, String _evaluador_1, String _conceptoEvaluador_1, String _fechaRevision_1, String _evaluador_2, String _conceptoEvaluador_2, String _fechaRevision_2)
  {
    codigo = _codigo;
    evaluador_1 = _evaluador_1;
    conceptoEvaluador_1 = _conceptoEvaluador_1;
    fechaRevision_1 = _fechaRevision_1;
    evaluador_2 = _evaluador_2;
    conceptoEvaluador_2 = _conceptoEvaluador_2;
    fechaRevision_2 = _fechaRevision_2;
  } // ctor

    public int getCodigo() {
        return codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    public String getEvaluador_1() {
        return evaluador_1;
    }

    public void setEvaluador_1(String evaluador_1) {
        this.evaluador_1 = evaluador_1;
    }

    public String getConceptoEvaluador_1() {
        return conceptoEvaluador_1;
    }

    public void setConceptoEvaluador_1(String conceptoEvaluador_1) {
        this.conceptoEvaluador_1 = conceptoEvaluador_1;
    }

    public String getFechaRevision_1() {
        return fechaRevision_1;
    }

    public void setFechaRevision_1(String fechaRevision_1) {
        this.fechaRevision_1 = fechaRevision_1;
    }

    public String getEvaluador_2() {
        return evaluador_2;
    }

    public void setEvaluador_2(String evaluador_2) {
        this.evaluador_2 = evaluador_2;
    }

    public String getConceptoEvaluador_2() {
        return conceptoEvaluador_2;
    }

    public void setConceptoEvaluador_2(String conceptoEvaluador_2) {
        this.conceptoEvaluador_2 = conceptoEvaluador_2;
    }

    public String getFechaRevision_2() {
        return fechaRevision_2;
    }

    public void setFechaRevision_2(String fechaRevision_2) {
        this.fechaRevision_2 = fechaRevision_2;
    }

  
} // class evaluadoresDTO
