package sop_corba.GestionAnteproyectosPackage;


/**
* sop_corba/GestionAnteproyectosPackage/usuarioDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaz.idl
* martes 30 de julio de 2019 20H58' COT
*/

public final class usuarioDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String nombreApellidos = "";
  public int identificacion = (int)0;
  public String usuarioUnicauca = "";
  public String contrasenia = "";
  public String tipoUsuario = "";

  public usuarioDTO ()
  {
  } // ctor

  public usuarioDTO (String _nombreApellidos, int _identificacion, String _usuarioUnicauca, String _contrasenia, String _tipoUsuario)
  {
    nombreApellidos = _nombreApellidos;
    identificacion = _identificacion;
    usuarioUnicauca = _usuarioUnicauca;
    contrasenia = _contrasenia;
    tipoUsuario = _tipoUsuario;
  } // ctor

    public String getNombreApellidos() {
        return nombreApellidos;
    }

    public void setNombreApellidos(String nombreApellidos) {
        this.nombreApellidos = nombreApellidos;
    }

    public int getIdentificacion() {
        return identificacion;
    }

    public void setIdentificacion(int identificacion) {
        this.identificacion = identificacion;
    }

    public String getUsuarioUnicauca() {
        return usuarioUnicauca;
    }

    public void setUsuarioUnicauca(String usuarioUnicauca) {
        this.usuarioUnicauca = usuarioUnicauca;
    }

    public String getContrasenia() {
        return contrasenia;
    }

    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }

    public String getTipoUsuario() {
        return tipoUsuario;
    }

    public void setTipoUsuario(String tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }

} // class usuarioDTO
