package sop_corba.GestionAnteproyectosPackage;


/**
* sop_corba/GestionAnteproyectosPackage/usuarioIngresadoDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaz.idl
* martes 30 de julio de 2019 20H58' COT
*/

public final class usuarioIngresadoDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int identificacion = (int)0;
  public String usuario = "";
  public String contrasenia = "";

  public usuarioIngresadoDTO ()
  {
  } // ctor

  public usuarioIngresadoDTO (int _identificacion, String _usuario, String _contrasenia)
  {
    identificacion = _identificacion;
    usuario = _usuario;
    contrasenia = _contrasenia;
  } // ctor

    public int getIdentificacion() {
        return identificacion;
    }

    public void setIdentificacion(int identificacion) {
        this.identificacion = identificacion;
    }

    public String getUsuario() {
        return usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public String getContrasenia() {
        return contrasenia;
    }

    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }

  
} // class usuarioIngresadoDTO
