package sop_corba.GestionAnteproyectosPackage;

/**
* sop_corba/GestionAnteproyectosPackage/usuarioDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaz.idl
* martes 30 de julio de 2019 20H58' COT
*/

public final class usuarioDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.GestionAnteproyectosPackage.usuarioDTO value = null;

  public usuarioDTOHolder ()
  {
  }

  public usuarioDTOHolder (sop_corba.GestionAnteproyectosPackage.usuarioDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.GestionAnteproyectosPackage.usuarioDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.GestionAnteproyectosPackage.usuarioDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.GestionAnteproyectosPackage.usuarioDTOHelper.type ();
  }

}
