package sop_corba.GestionAnteproyectosPackage;

/**
* sop_corba/GestionAnteproyectosPackage/usuarioIngresadoDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaz.idl
* martes 30 de julio de 2019 20H58' COT
*/

public final class usuarioIngresadoDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.GestionAnteproyectosPackage.usuarioIngresadoDTO value = null;

  public usuarioIngresadoDTOHolder ()
  {
  }

  public usuarioIngresadoDTOHolder (sop_corba.GestionAnteproyectosPackage.usuarioIngresadoDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.GestionAnteproyectosPackage.usuarioIngresadoDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.GestionAnteproyectosPackage.usuarioIngresadoDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.GestionAnteproyectosPackage.usuarioIngresadoDTOHelper.type ();
  }

}
