package servidor.DTO;

import sop_corba.GestionAnteproyectosPackage.*;


/**
* sop_corba/GestionAnteproyectosPackage/usuarioIngresadoDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interfaz.idl
* martes 23 de julio de 2019 22H42' COT
*/

public final class usuarioIngresadoDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int identificacion = 0;
  public String usuario = null;
  public String contrasenia = null;

  public usuarioIngresadoDTO ()
  {
  } // ctor

  public usuarioIngresadoDTO (String _usuario, String _contrasenia, int _identificacion)
  {
    usuario = _usuario;
    contrasenia = _contrasenia;
    identificacion = _identificacion;
  } // ctor

    public String getUsuario() {
        return usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public String getContrasenia() {
        return contrasenia;
    }

    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }

    public int getIdentificacion() {
        return identificacion;
    }

    public void setIdentificacion(int identificacion) {
        this.identificacion = identificacion;
    }
    
    
  
} // class usuarioIngresadoDTO
